{
  "type": "unknown",
  "name": "runCatching",
  "signatures": [
    {
      "text": "inline fun <R> runCatching(block: () -> R): Result<R>",
      "desc": "Calls the specified function block and returns its encapsulated result if invocation was successful, catching any Throwable exception that was thrown from the block function execution and encapsulating it as a failure."
    },
    {
      "text": "inline fun <T, R> T.runCatching(block: T.() -> R): Result<R>",
      "desc": "Calls the specified function block with this value as its receiver and returns its encapsulated result if invocation was successful, catching any Throwable exception that was thrown from the block function execution and encapsulating it as a failure."
    }
  ],
  "items": []
}