{
  "type": "unknown",
  "name": "resumeWithException",
  "signature": "fun <T> Continuation<T>.resumeWithException( exception: Throwable)",
  "items": []
}